application.ymlspring:
  application:
    name: greeting-service
  cloud:
    config:
      enabled: false
greeting-service:
  greeting: "Hello"
  default-value: "Word"
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'